
server:
  servlet:
    port: 8898
    contextPath: /api

spring:

  application:
    name: myntra-api

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/myntra-db
    username: postgres
    password: ashruti

  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
